"use client"
import './globals.css'
import React,{useState,useEffect} from "react"
import { Inter } from 'next/font/google'
import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import IconButton from '@mui/material/IconButton';
import MenuIcon from '@mui/icons-material/Menu';
import Popover from '@mui/material/Popover';
import { Divider } from '@mui/material';
import Prvider from './Redux/Prvider';
import { useSelector } from 'react-redux';
import NavBar from './NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <Prvider>
          <NavBar/>
          {children}
        </Prvider>
       
        </body>
    </html>
  )
}
